Change the build system and generate a universal ES5/UMD version
lukechilds/when-dom-ready pull request #6
Opened 2017-01-31 08:13 UTC by Offirmo

as discussed in #5

Thanks, I learned a lot looking at your module dev tooling. And while I knew it was possible, I never did the typescript build yet.

2017-01-31 08:18 UTC, Offirmo commented
Since you module don't do a heavy usage of ES6, I saw no need to generate optimized variants (ex. ES6 / UMD)

2017-01-31 11:33 UTC, lukechilds requested changes
Thanks for taking the time to put this together. I definitely think this is a good idea.

I've added my comments. Ideally we just need `npm run build` to build `dist/umd/index.js` and `dist/es2015/index.js` with the smallest tsconfig possible. Arrow fns and Array.includes need to be transpiled for both umd and es2015 formats.

2017-01-31 11:33 UTC, lukechilds commented on package.json
> +  "jsnext:main": "src/index.js",
This should be `module` instead of `jsnext:main`.

Also, it will still need to be transpiled so arrow fns and Array.includes work in Safari and IE.

2017-01-31 11:33 UTC, lukechilds commented on build/es5.umd/tsconfig.json
> +{
Do we need all these tsconfig files? If we can have one file (as small as possible) in the root of the project, that would be ideal.

2017-01-31 11:33 UTC, lukechilds commented on package.json
> +    "build:es5.umd": "tsc --project build/es5.umd",
This should just be `build`.

2017-02-01 01:03 UTC, Offirmo commented on package.json
> +  "jsnext:main": "src/index.js",
Interisting. I don't know this kind of exposure. Could you share a reference ?

2017-02-01 01:04 UTC, Offirmo commented on build/es5.umd/tsconfig.json
> +{
Yes, we can definitely make it simpler. It was a demo on how we could build as much variants as we want.

We'll still need at last one tsconfig per variant.

2017-02-01 01:05 UTC, Offirmo commented on package.json
> +  "jsnext:main": "src/index.js",
Just in case, `jsnext:main` is a proposal from rollup and is supposed to point at an ES6+ version.

2017-02-01 01:18 UTC, Offirmo commented
about the naming, "UMD" refers to the module interface. We need to also specify the language support level, aka. "ES5"' "ES6", "ES7"...

In my opinion, since your module doesn't make a heavy usage of ES6+, sharing an ES6 (for modern bundlers) and a "conservative" ES5+UMD for standalone / old browsers is the best.

I'll simplify the build system.

2017-02-01 05:46 UTC, lukechilds commented on package.json
> +  "jsnext:main": "src/index.js",
Yeah `module` is the same but more likely to be standardised: https://github.com/rollup/rollup/wiki/pkg.module

2017-02-01 05:58 UTC, lukechilds commented
Both modules formats should be transpiled with the same settings. Otherwise if people include rollup in their build system it'll reduce browser compatibility.

2017-02-06 11:52 UTC, closed without merging

2017-02-06 11:53 UTC, Offirmo commented
Hi, I'm a bit delayed. I'm a nomad and currently changing location.

I'll close this PR and send a new one taking comments into account !

2017-02-06 11:54 UTC, Offirmo commented on package.json
> +  "jsnext:main": "src/index.js",
How interesting ! Thanks for the info. (We really profit when contributing to open source)

2017-02-06 13:03 UTC, lukechilds commented
> I'm a nomad and currently changing location.

I feel you, just spent all day sorting out a border run 👌